config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  
  resources :bands do 
    resources :albums, only: [:new]
  end 
  
  resources :albums, only: [:create, :edit, :show, :update, :destroy]
  
  
end

app/models/album.rb
class Album < ApplicationRecord
  
  validates_presence_of :band_id, :title, :year, :studio
  
  belongs_to :band
  has_many :tracks, dependent: :destroy

    
  
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  
  validates :name, presence:true
  
  has_many :albums, dependent: :destroy
  has_many :tracks, through: :albums, dependent: :destroy


  
end 

app/models/track.rb
class Track < ApplicationRecord
  
  validates_presence_of :album_id, :title, :ord, :bonus
  
  belongs_to :album
  has_one :band
  
  
end

app/models/user.rb
class User < ApplicationRecord
  
  after_initialize :ensure_session_token  

  validates :email, presence: true, uniqueness:true
  validates :password, length: {minimum: 6, allow_nil: true}
  validates :password_digest, presence:true
  validates :session_token, presence:true, uniqueness:true
  
  
  attr_reader :password
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end 
  
  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end 
  
  def self.find_by_credentials(email, password)
      user = User.find_by(email: email)
      return nil if user.nil?
      user.is_password?(password) ? user : nil 
    end 
  
  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end 
  
  def ensure_session_token
    session_token ||= SecureRandom.urlsafe_base64
  end 
    
end 

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

    def new
      @album = Album.new
    end 

    def create
      @album = Album.new(album_params)

      if @album.save
        redirect_to album_url(@album)
      else 
        flash[:errors] = "Oops, something happened! Try again."
        render :new
      end
    end

    def show
      @album = Album.find_by(id: params[:id])
      render :show  
    end  

    def edit
      @album = Album.find_by(id: params[:id])
      render :edit
    end 

    def update
      @album = Album.find_by(id: params[:id])
      
      if @album.update_attributes(band_params)
        redirect_to band_url(@album)
      else 
        flash[:errors] = "Something went wrong, try again."
        render :edit 
      end 
    end 

    def destroy
      @album = Album.find_by(id: params[:id])
      @album.delete
      redirect_to bands_url
    end

    def album_params 
      params.require(:album).permit(:band_id, :title, :year, :studio)
    end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :require_login
  
  def login(user)
    session[:session_token] = user.reset_session_token!
    @current_user
  end 
  
  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end 
  
  def require_login
    redirect_to new_session_url unless logged_in?
  end 
  
  def logged_in?
    !!current_user
  end 
  
  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil 
  end 
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  # helper_function :all_bands
  # 
  # def all_bands
  #   Band.all 
  # end 
  
  def index 
    @bands = Band.all 
    render :index
  end 
  
  def new
    @band = Band.new
    render :new
  end 
  
  def create
    @band = Band.new(band_params)
    
    if @band.save
      redirect_to band_url(@band)
    else
      flash[:errors] = "You need to enter a band name!"
      render :new
    end 
  end
  
  def edit
    @band = Band.find_by(id: params[:id])
  end 
  
  def show 
    @band = Band.find_by(id: params[:id])
    render :show
  end 
  
  def update
    @band = Band.find_by(id: params[:id])
    
    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else 
      flash[:errors] = "Something went wrong, try again."
      render :edit 
    end 
  end 
  
  def destroy
    @band = Band.find_by(id: params[:id])
    @band.delete
    redirect_to bands_url
  end 
  
  def band_params
    params.require(:band).permit(:name)
  end 
  
  
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    
  end 
  
  def create 
    @user = User.find_by_credentials(
          params[:user][:email],
          params[:user][:password])
    
    if @user 
      login(@user)
      redirect_to user_url(@user)
    else 
      flash[:errors] = "Your credentials are incorrect, try again"
      redirect_to new_session_url 
    end 
  end 
  
  def destroy 
    logout
    redirect_to new_session_url
  end 
  
  def session_params
    params.require(:user).permit(:email, :password)
  end  
    
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    render :new #default behavior
  end 
  
  def create 
    @user = User.new(user_params)
  
    if @user 
      login(@user)
      redirect_to user_url(@user) #redirect to their page
    else 
      flash.now[:errors] = "Your password is too short, or that email is already taken! Try again!"
      render :new #want to render instead redirect becauser of the flash.now
      #could redirect if I user flash instead of flash.now
    end 
  end 
  
  def show #look at the wildcard id and find the user by that, then render their page... @user gets passed to the view page
    @user = User.find_by(id: params[:id])
    render :show  #render their page, this is a default, not needed to be put
  end 
  
  def user_params 
    params.require(:user).permit(:email, :password)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/edit.html.erb
<h1>ALbum edit page</h1>

<% if flash[:errors] %>
<%= flash[:errors] %>
<% end %>

<form action="<%=  albums_url %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
    
  <label>Band</label>
  <select name="album[band_id]">
    <option disabled >Select A Band</option>

    <% Band.all.each do |band| %>
    <option value="<%= band.id %>"<%= params[:band_id] = band.id ? "selected" : "" %> ><%= band.name %></option>
    <% end %>
  </select>
  
    
  <label>Title</label>
  <input type="text" name="album[title]" value="<%= album.title %>">


  <label>Release Year</label>
  <input type="text" name="album[year]">
  
  <label>Type of Recording</label>
  <input type="radio" name="album[studio]" value="<%= "checked" if params[:studio] = true %>">Studio 
  <input type="radio" name="album[studio]" value="<%= "checked" if params[:studio] = false %>">Live

  <br>
  <input type="submit" value="Submit">
  
  
  
</form>

app/views/albums/new.html.erb
<h1>Add an Album</h1>

<% if flash[:errors] %>
<%= flash[:errors] %>
<% end %>

<form action="<%=  albums_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
    
  <label>Band</label>
  <select name="album[band_id]">
    <option disabled >Select A Band</option>

    <% Band.all.each do |band| %>
    <option value="<%= band.id %>"<%= params[:band_id] = band.id ? "selected" : "" %> ><%= band.name %></option>
    <% end %>
  </select>
  
    
  <label>Title</label>
  <input type="text" name="album[title]">


  <label>Release Year</label>
  <input type="text" name="album[year]">
  
  <label>Type of Recording</label>
  <input type="radio" name="album[studio]">Studio
  <input type="radio" name="album[studio]">Live

  <br>
  <input type="submit" value="Submit">
  
  
  
</form>

app/views/albums/show.html.erb
<h1> <%= Band.find_by(id: @album.band_id).name %>><%= @album.title %> </h1>

  <li> Release Year:<%= @album.year %></li>
  <li>Album Type: <%= @album.studio ? "Studio" : "Live" %>

  <br>
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="Delete">

app/views/bands/edit.html.erb
<h1>This is the band edit page....</h1>

<% if flash[:errors] %>
<%= flash[:errors] %>
<% end %>

<form action="<%= band_url(@band) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  <label>Edit Name:</label>
  <input type="text" name="band[name]" value="<%= @band.name %>">
  <br>
  <input type="submit" value="Submit Changes">
  
</form> 
  

app/views/bands/index.html.erb
<form action=" <%= users_url %> " method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  

<h1>All Bands</h1>

<a href="<%= new_band_url %>">Add Band</a>

<section>
  <% @bands.each do |band| %>

  <li>
    <a href="<%= band_url(band) %>"><%= band.name %></a>
    <br>
  </li>
  
  <% end %>

</section>

app/views/bands/new.html.erb
<h1>Add A Band</h1>
<% if flash[:errors] %>
<%= flash[:errors] %>
<% end %>

<form action=" <%= bands_url %> " method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
<label>Name</label>
<input type="text" name="band[name]">

<input type="submit" value="Submit">
  
</form>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<a href="<%= bands_url %>">Back to All Bands</a>
<br>

<h2>Albums</h2>
<ul>
  <% @band.albums.each do |album| %>
  <li><a href="album_url(@album)"></a><%=  album.title  %></li>
  <% end %>
</ul>

<form action=" <%= band_url %> " method="post">
  <input type="hidden" name="authenticity_token" value=" <%= form_authenticity_token %> ">
  
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="Delete Band Entry">
  
  
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>***Music App***</h1>
    <div>
      <% if current_user.nil? %>
        <a href="<%= new_user_url %>">Sign Up</a>
        <a href="<%= new_session_url %>">Sign In</a>
      <% else %>
        <%= current_user.email %>
        <form action="<%= session_url %>" method="post">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <input type="hidden" name="_method" value="delete">
          <input type="submit" value="Sign Out">
        </form>
      <% end %>
    </div>
    
    <main>
    <%= yield %>  
    </main>
    
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action=" <%= users_url %> " method="post">
  <input type="hidden" name="authenticity_token" value=" <%= form_authenticity_token %> ">
  
<label>Email</label>
<input type="email" name="user[email]">

<br>

<label>Password</label>
<input type="password" name="user[password]">

<input type="submit" value="Submit">
  
</form>

app/views/users/show.html.erb
<h1> Welcome to the page of <%= @user.email %> </h1>


  <input type="hidden" name="authenticity_token" value=" <%= form_authenticity_token %> ">